### ISSUE TITLE
le reinit fails when local logs specified in configuration file

### ISSUE THREAD

**Issue by joeheung** [logentries/le#72]
```[syslog]
path=/var/log/syslog
token=00000000-1111-2222-3333-444444444444
```

Note when the above snippet is in the config and we run le reinit, we get the following error

```
le reinit --pull-server-side-config=False --suppress-ssl --datahub=127.0.0.1:10000
Traceback (most recent call last):
  File "/usr/bin/le", line 9, in <module>
    load_entry_point('logentries==1.4.5', 'console_scripts', 'le')()
  File "/usr/share/logentries/logentries/le.py", line 2900, in main
    return func(args[1:])
  File "/usr/share/logentries/logentries/le.py", line 2345, in cmd_reinit
    config.save()
  File "/usr/share/logentries/logentries/le.py", line 1858, in save
    conf.set(clog.name, TOKEN_PARAM, clog.token)
  File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'syslog'
```

**Comment by vilda** [comment]
I cannot reproduce it, those commands work for me. Can you pinpoint when is this trigerred @joeheung ?

**Comment by joeheung** [comment]
Sorry @vilda, should have given you more info when opening this bug.

Install the agent
```
apt-get install logentries
touch /etc/default/logentries_not_to_be_run
apt-get install logentries-daemon
```
First initialization
```
le reinit --pull-server-side-config=False --suppress-ssl --datahub=127.0.0.1:10000
Reinitialized
```

Append a log to your config 

```
vi /etc/le/config

[syslog]
path=/var/log/syslog
token=00000000-1111-2222-3333-444444444444
```

Reinitialize
```
le reinit --pull-server-side-config=False --suppress-ssl --datahub=127.0.0.1:10000
Traceback (most recent call last):
  File "/usr/bin/le", line 9, in <module>
    load_entry_point('logentries==1.4.5', 'console_scripts', 'le')()
  File "/usr/share/logentries/logentries/le.py", line 2900, in main
    return func(args[1:])
  File "/usr/share/logentries/logentries/le.py", line 2345, in cmd_reinit
    config.save()
  File "/usr/share/logentries/logentries/le.py", line 1858, in save
    conf.set(clog.name, TOKEN_PARAM, clog.token)
  File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'syslog'
```

**Comment by vilda** [comment]
Seems to be fixed...
